/*
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation:
  /nix/store/c9m211bm84ncjmaxx27ki9dymd4qkwm2-ocaml4.14.1-eurydice-dirty/eurydice
  --config ../c.yaml ../../libcrux_ml_kem.llbc F* version: <unknown> KaRaMeL
  version: <unknown>
 */

#ifndef __libcrux_intrinsics_avx2_H
#define __libcrux_intrinsics_avx2_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "eurydice_glue.h"
#include "immintrin.h"

typedef __m128i core_core_arch_x86___m128i;
typedef __m256i core_core_arch_x86___m256i;

// Cast and Convert

static inline core_core_arch_x86___m128i mm256_castsi256_si128(
    core_core_arch_x86___m256i a) {
  return _mm256_castsi256_si128(a);
}

static inline core_core_arch_x86___m256i mm256_cvtepi16_epi32(
    core_core_arch_x86___m128i a) {
  return _mm256_cvtepi16_epi32(a);
}

static inline core_core_arch_x86___m256i mm256_castsi128_si256(
    core_core_arch_x86___m128i a) {
  return _mm256_castsi128_si256(a);
}

// Initialize, Load, Store

static inline core_core_arch_x86___m256i mm256_setzero_si256(void) {
  return _mm256_setzero_si256();
}

static inline core_core_arch_x86___m256i mm256_set1_epi16(int16_t a) {
  return _mm256_set1_epi16(a);
}

static inline core_core_arch_x86___m256i mm256_set1_epi32(int32_t a) {
  return _mm256_set1_epi32(a);
}

static inline core_core_arch_x86___m256i mm256_set1_epi64x(int64_t a) {
  return _mm256_set1_epi64x(a);
}

static inline core_core_arch_x86___m128i mm_set1_epi16(int16_t a) {
  return _mm_set1_epi16(a);
}

static inline core_core_arch_x86___m256i mm256_set_epi16(
    int16_t x0, int16_t x1, int16_t x2, int16_t x3, int16_t x4, int16_t x5,
    int16_t x6, int16_t x7, int16_t x8, int16_t x9, int16_t x10, int16_t x11,
    int16_t x12, int16_t x13, int16_t x14, int16_t x15) {
  return _mm256_set_epi16(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12,
                          x13, x14, x15);
}

static inline core_core_arch_x86___m256i mm256_set_epi8(
    int8_t x0, int8_t x1, int8_t x2, int8_t x3, int8_t x4, int8_t x5, int8_t x6,
    int8_t x7, int8_t x8, int8_t x9, int8_t x10, int8_t x11, int8_t x12,
    int8_t x13, int8_t x14, int8_t x15, int8_t x16, int8_t x17, int8_t x18,
    int8_t x19, int8_t x20, int8_t x21, int8_t x22, int8_t x23, int8_t x24,
    int8_t x25, int8_t x26, int8_t x27, int8_t x28, int8_t x29, int8_t x30,
    int8_t x31) {
  return _mm256_set_epi8(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12,
                         x13, x14, x15, x16, x17, x18, x19, x20, x21, x22, x23,
                         x24, x25, x26, x27, x28, x29, x30, x31);
}

static inline core_core_arch_x86___m128i mm_set_epi8(
    uint8_t x0, uint8_t x1, uint8_t x2, uint8_t x3, uint8_t x4, uint8_t x5,
    uint8_t x6, uint8_t x7, uint8_t x8, uint8_t x9, uint8_t x10, uint8_t x11,
    uint8_t x12, uint8_t x13, uint8_t x14, uint8_t x15) {
  return _mm_set_epi8(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12,
                      x13, x14, x15);
}

static inline core_core_arch_x86___m256i mm256_set_epi32(int32_t x0, int32_t x1,
                                                         int32_t x2, int32_t x3,
                                                         int32_t x4, int32_t x5,
                                                         int32_t x6,
                                                         int32_t x7) {
  return _mm256_set_epi32(x0, x1, x2, x3, x4, x5, x6, x7);
}

static inline core_core_arch_x86___m256i mm256_loadu_si256_i16(
    Eurydice_borrow_slice_i16 a) {
  return _mm256_loadu_si256((const __m256i*)a.ptr);
}

static inline core_core_arch_x86___m256i mm256_loadu_si256_u8(
    Eurydice_borrow_slice_u8 a) {
  return _mm256_loadu_si256((const __m256i*)a.ptr);
}

static inline core_core_arch_x86___m128i mm_loadu_si128(Eurydice_borrow_slice_u8 a) {
  return _mm_loadu_si128((const __m128i*)a.ptr);
}

static inline void mm_storeu_bytes_si128(Eurydice_mut_borrow_slice_u8 a,
                                         core_core_arch_x86___m128i b) {
  _mm_storeu_si128((__m128i*)a.ptr, b);
}

static inline void mm256_storeu_si256_i16(Eurydice_mut_borrow_slice_i16 a,
                                          core_core_arch_x86___m256i b) {
  _mm256_storeu_si256((__m256i*)a.ptr, b);
}

static inline void mm256_storeu_si256_u8(Eurydice_mut_borrow_slice_u8 a,
                                         core_core_arch_x86___m256i b) {
  _mm256_storeu_si256((__m256i*)a.ptr, b);
}

static inline void mm_storeu_si128(Eurydice_mut_borrow_slice_i16 a,
                                   core_core_arch_x86___m128i b) {
  _mm_storeu_si128((__m128i*)a.ptr, b);
}

// Arithmetic: Add, Sub

static inline core_core_arch_x86___m256i mm256_add_epi16(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_add_epi16(a, b);
}

static inline core_core_arch_x86___m256i mm256_add_epi32(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_add_epi32(a, b);
}

static inline core_core_arch_x86___m128i mm_add_epi16(
    core_core_arch_x86___m128i a, core_core_arch_x86___m128i b) {
  return _mm_add_epi16(a, b);
}

static inline core_core_arch_x86___m256i mm256_sub_epi16(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_sub_epi16(a, b);
}

static inline core_core_arch_x86___m128i mm_sub_epi16(
    core_core_arch_x86___m128i a, core_core_arch_x86___m128i b) {
  return _mm_sub_epi16(a, b);
}

// Arithmetic: Mul low and high, Mul-Add combinations

static inline core_core_arch_x86___m256i mm256_mullo_epi16(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_mullo_epi16(a, b);
}

static inline core_core_arch_x86___m256i mm256_mulhi_epi16(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_mulhi_epi16(a, b);
}

static inline core_core_arch_x86___m256i mm256_mul_epu32(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_mul_epu32(a, b);
}

static inline core_core_arch_x86___m256i mm256_mullo_epi32(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_mullo_epi32(a, b);
}

static inline core_core_arch_x86___m128i mm_mullo_epi16(
    core_core_arch_x86___m128i a, core_core_arch_x86___m128i b) {
  return _mm_mullo_epi16(a, b);
}

static inline core_core_arch_x86___m128i mm_mulhi_epi16(
    core_core_arch_x86___m128i a, core_core_arch_x86___m128i b) {
  return _mm_mulhi_epi16(a, b);
}

static inline core_core_arch_x86___m256i mm256_madd_epi16(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_madd_epi16(a, b);
}

// Comparison

static inline core_core_arch_x86___m256i mm256_cmpgt_epi16(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_cmpgt_epi16(a, b);
}

// Bitwise operations

static inline core_core_arch_x86___m256i mm256_and_si256(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_and_si256(a, b);
}

static inline core_core_arch_x86___m256i mm256_andnot_si256(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_andnot_si256(a, b);
}

static inline core_core_arch_x86___m256i mm256_xor_si256(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_xor_si256(a, b);
}

static inline int32_t mm_movemask_epi8(core_core_arch_x86___m128i a) {
  return _mm_movemask_epi8(a);
}

// Shift operations
#define mm256_srai_epi16(a, b, _) (_mm256_srai_epi16(b, a))

#define mm256_srli_epi16(a, b, _) (_mm256_srli_epi16(b, a))

#define mm256_slli_epi16(a, b, _) (_mm256_slli_epi16(b, a))

#define mm256_slli_epi32(a, b, _) (_mm256_slli_epi32(b, a))

static inline core_core_arch_x86___m256i mm256_slli_epi64_(
    int32_t a, core_core_arch_x86___m256i b) {
  return _mm256_slli_epi64(b, a);
}

#define mm256_slli_epi64(a, b, c) (mm256_slli_epi64_(a, b))

#define mm256_srai_epi32(a, b, _) (_mm256_srai_epi32(b, a))

#define mm256_srli_epi32(a, b, _) (_mm256_srli_epi32(b, a))

static inline core_core_arch_x86___m256i mm256_sllv_epi32(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_sllv_epi32(a, b);
}

static inline core_core_arch_x86___m256i mm256_srli_epi64_(
    int32_t a, core_core_arch_x86___m256i b) {
  return _mm256_srli_epi64(b, a);
}

#define mm256_srli_epi64(a, b, c) (mm256_srli_epi64_(a, b))

// Shuffle and Vector Interleaving

static inline core_core_arch_x86___m256i mm256_unpacklo_epi32(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_unpacklo_epi32(a, b);
}

static inline core_core_arch_x86___m256i mm256_unpacklo_epi64(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_unpacklo_epi64(a, b);
}

static inline core_core_arch_x86___m256i mm256_unpackhi_epi32(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_unpackhi_epi32(a, b);
}

static inline core_core_arch_x86___m256i mm256_unpackhi_epi64(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_unpackhi_epi64(a, b);
}

static inline core_core_arch_x86___m256i mm256_packs_epi32(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_packs_epi32(a, b);
}

static inline core_core_arch_x86___m128i mm_packs_epi16(
    core_core_arch_x86___m128i a, core_core_arch_x86___m128i b) {
  return _mm_packs_epi16(a, b);
}

#define mm256_shuffle_epi32(a, b, _) (_mm256_shuffle_epi32(b, a))

#define mm256_extracti128_si256(a, b, _) (_mm256_extracti128_si256(b, a))

#define mm256_permute4x64_epi64(a, b, _) (_mm256_permute4x64_epi64(b, a))

#define mm256_permute2x128_si256(a, b, c, d) \
  (_mm256_permute2x128_si256(b, c, a))

#define mm256_inserti128_si256(a, b, c, _) (_mm256_inserti128_si256(b, c, a))

#define mm256_blend_epi16(a, b, c, _) (_mm256_blend_epi16(b, c, a))

// Charon --monomorphize emits one C symbol per const-generic immediate value.
// Keep the generic macros above for older Eurydice output, and expose concrete
// wrappers below so the immediate operands remain compile-time constants.
#define LIBCRUX_AVX2_IMM_M256(name, intrinsic, imm)                         \
  static inline core_core_arch_x86___m256i name(                            \
      core_core_arch_x86___m256i a) {                                       \
    return intrinsic(a, imm);                                               \
  }

#define LIBCRUX_AVX2_IMM_M128(name, intrinsic, imm)                         \
  static inline core_core_arch_x86___m128i name(                            \
      core_core_arch_x86___m256i a) {                                       \
    return intrinsic(a, imm);                                               \
  }

#define LIBCRUX_AVX2_IMM2_M256(name, intrinsic, imm)                        \
  static inline core_core_arch_x86___m256i name(                            \
      core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {         \
    return intrinsic(a, b, imm);                                            \
  }

#define LIBCRUX_AVX2_INSERTI128(name, imm)                                  \
  static inline core_core_arch_x86___m256i name(                            \
      core_core_arch_x86___m256i a, core_core_arch_x86___m128i b) {         \
    return _mm256_inserti128_si256(a, b, imm);                              \
  }

LIBCRUX_AVX2_IMM_M256(mm256_srai_epi16___10___i32_, _mm256_srai_epi16, 10)
LIBCRUX_AVX2_IMM_M256(mm256_srai_epi16___15___i32_, _mm256_srai_epi16, 15)
LIBCRUX_AVX2_IMM_M256(mm256_srai_epi32___16___i32_, _mm256_srai_epi32, 16)

LIBCRUX_AVX2_IMM_M256(mm256_srli_epi16___4___i32_, _mm256_srli_epi16, 4)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi16___6___i32_, _mm256_srli_epi16, 6)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi16___11___i32_, _mm256_srli_epi16, 11)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi16___15___i32_, _mm256_srli_epi16, 15)

LIBCRUX_AVX2_IMM_M256(mm256_srli_epi32___1___i32_, _mm256_srli_epi32, 1)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi32___3___i32_, _mm256_srli_epi32, 3)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi32___4___i32_, _mm256_srli_epi32, 4)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi32___5___i32_, _mm256_srli_epi32, 5)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi32___10___i32_, _mm256_srli_epi32, 10)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi32___11___i32_, _mm256_srli_epi32, 11)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi32___16___i32_, _mm256_srli_epi32, 16)

LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___2___i32_, _mm256_srli_epi64, 2)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___3___i32_, _mm256_srli_epi64, 3)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___8___i32_, _mm256_srli_epi64, 8)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___9___i32_, _mm256_srli_epi64, 9)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___12___i32_, _mm256_srli_epi64, 12)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___19___i32_, _mm256_srli_epi64, 19)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___20___i32_, _mm256_srli_epi64, 20)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___21___i32_, _mm256_srli_epi64, 21)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___22___i32_, _mm256_srli_epi64, 22)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___23___i32_, _mm256_srli_epi64, 23)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___25___i32_, _mm256_srli_epi64, 25)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___28___i32_, _mm256_srli_epi64, 28)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___36___i32_, _mm256_srli_epi64, 36)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___37___i32_, _mm256_srli_epi64, 37)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___39___i32_, _mm256_srli_epi64, 39)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___43___i32_, _mm256_srli_epi64, 43)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___44___i32_, _mm256_srli_epi64, 44)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___46___i32_, _mm256_srli_epi64, 46)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___49___i32_, _mm256_srli_epi64, 49)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___50___i32_, _mm256_srli_epi64, 50)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___54___i32_, _mm256_srli_epi64, 54)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___56___i32_, _mm256_srli_epi64, 56)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___58___i32_, _mm256_srli_epi64, 58)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___61___i32_, _mm256_srli_epi64, 61)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___62___i32_, _mm256_srli_epi64, 62)
LIBCRUX_AVX2_IMM_M256(mm256_srli_epi64___63___i32_, _mm256_srli_epi64, 63)

LIBCRUX_AVX2_IMM_M256(mm256_slli_epi16___15___i32_, _mm256_slli_epi16, 15)

LIBCRUX_AVX2_IMM_M256(mm256_slli_epi32___1___i32_, _mm256_slli_epi32, 1)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi32___4___i32_, _mm256_slli_epi32, 4)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi32___5___i32_, _mm256_slli_epi32, 5)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi32___10___i32_, _mm256_slli_epi32, 10)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi32___11___i32_, _mm256_slli_epi32, 11)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi32___16___i32_, _mm256_slli_epi32, 16)

LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___1___i32_, _mm256_slli_epi64, 1)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___2___i32_, _mm256_slli_epi64, 2)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___3___i32_, _mm256_slli_epi64, 3)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___6___i32_, _mm256_slli_epi64, 6)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___8___i32_, _mm256_slli_epi64, 8)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___10___i32_, _mm256_slli_epi64, 10)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___14___i32_, _mm256_slli_epi64, 14)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___15___i32_, _mm256_slli_epi64, 15)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___18___i32_, _mm256_slli_epi64, 18)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___20___i32_, _mm256_slli_epi64, 20)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___21___i32_, _mm256_slli_epi64, 21)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___25___i32_, _mm256_slli_epi64, 25)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___27___i32_, _mm256_slli_epi64, 27)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___28___i32_, _mm256_slli_epi64, 28)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___36___i32_, _mm256_slli_epi64, 36)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___39___i32_, _mm256_slli_epi64, 39)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___41___i32_, _mm256_slli_epi64, 41)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___43___i32_, _mm256_slli_epi64, 43)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___44___i32_, _mm256_slli_epi64, 44)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___45___i32_, _mm256_slli_epi64, 45)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___55___i32_, _mm256_slli_epi64, 55)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___56___i32_, _mm256_slli_epi64, 56)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___61___i32_, _mm256_slli_epi64, 61)
LIBCRUX_AVX2_IMM_M256(mm256_slli_epi64___62___i32_, _mm256_slli_epi64, 62)

LIBCRUX_AVX2_IMM_M256(mm256_shuffle_epi32___8___i32_, _mm256_shuffle_epi32, 8)
LIBCRUX_AVX2_IMM_M256(mm256_shuffle_epi32___68___i32_, _mm256_shuffle_epi32, 68)
LIBCRUX_AVX2_IMM_M256(mm256_shuffle_epi32___160___i32_, _mm256_shuffle_epi32, 160)
LIBCRUX_AVX2_IMM_M256(mm256_shuffle_epi32___238___i32_, _mm256_shuffle_epi32, 238)
LIBCRUX_AVX2_IMM_M256(mm256_shuffle_epi32___245___i32_, _mm256_shuffle_epi32, 245)

LIBCRUX_AVX2_IMM_M128(mm256_extracti128_si256___1___i32_,
                      _mm256_extracti128_si256, 1)

LIBCRUX_AVX2_IMM_M256(mm256_permute4x64_epi64___160___i32_,
                      _mm256_permute4x64_epi64, 160)
LIBCRUX_AVX2_IMM_M256(mm256_permute4x64_epi64___216___i32_,
                      _mm256_permute4x64_epi64, 216)
LIBCRUX_AVX2_IMM_M256(mm256_permute4x64_epi64___245___i32_,
                      _mm256_permute4x64_epi64, 245)

LIBCRUX_AVX2_IMM2_M256(mm256_permute2x128_si256___32___i32_,
                       _mm256_permute2x128_si256, 32)
LIBCRUX_AVX2_IMM2_M256(mm256_permute2x128_si256___49___i32_,
                       _mm256_permute2x128_si256, 49)

LIBCRUX_AVX2_INSERTI128(mm256_inserti128_si256___1___i32_, 1)

LIBCRUX_AVX2_IMM2_M256(mm256_blend_epi16___170___i32_, _mm256_blend_epi16,
                       170)
LIBCRUX_AVX2_IMM2_M256(mm256_blend_epi16___204___i32_, _mm256_blend_epi16,
                       204)
LIBCRUX_AVX2_IMM2_M256(mm256_blend_epi16___240___i32_, _mm256_blend_epi16,
                       240)

#undef LIBCRUX_AVX2_INSERTI128
#undef LIBCRUX_AVX2_IMM2_M256
#undef LIBCRUX_AVX2_IMM_M128
#undef LIBCRUX_AVX2_IMM_M256

static inline core_core_arch_x86___m256i mm256_shuffle_epi8(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_shuffle_epi8(a, b);
}

static inline core_core_arch_x86___m256i mm256_permutevar8x32_epi32(
    core_core_arch_x86___m256i a, core_core_arch_x86___m256i b) {
  return _mm256_permutevar8x32_epi32(a, b);
}

static inline core_core_arch_x86___m128i mm_shuffle_epi8(
    core_core_arch_x86___m128i a, core_core_arch_x86___m128i b) {
  return _mm_shuffle_epi8(a, b);
}

#if defined(__cplusplus)
}
#endif

#define __libcrux_intrinsics_avx2_H_DEFINED
#endif
