name: Build Eurydice with latest F* and Karamel

on:
  schedule:
  - cron: "0 0 * * *" # every day

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Update dependencies
        run: |
          for input in fstar karamel charon; do
              nix flake update --update-input $input
          done
      - name: Build and test
        run: nix flake check
