name: Build Eurydice and run tests

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        run: nix flake check -L

  check-charon-pin:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # deep clone in order to get access to other commits
      - run: nix develop '.#ci' --command ./scripts/ci-check-charon-pin.sh

  kyber:
    needs: [check]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          # Flake overrides aren't recursive: if I want to use eurydice with
          # all its dependencies, I must override each of them.
          CHARON_REV="$(nix develop '.#ci' --command jq -r .nodes.charon.locked.rev flake.lock)"
          KRML_REV="$(nix develop '.#ci' --command jq -r .nodes.karamel.locked.rev flake.lock)"
          FSTAR_REV="$(nix develop '.#ci' --command jq -r .nodes.fstar.locked.rev flake.lock)"
          git clone https://github.com/cryspen/libcrux
          cd libcrux
          nix develop --command cargo generate-lockfile
          nix build --refresh -L '.#ml-kem' \
              --override-input eurydice github:aeneasverif/eurydice/${{ github.sha }} \
              --override-input charon github:aeneasverif/charon/$CHARON_REV \
              --override-input karamel github:FStarLang/karamel/$KRML_REV \
              --override-input fstar github:FStarLang/fstar/$FSTAR_REV \
              --override-input eurydice/charon github:aeneasverif/charon/$CHARON_REV \
              --override-input eurydice/karamel github:FStarLang/karamel/$KRML_REV \
              --override-input eurydice/fstar github:FStarLang/fstar/$FSTAR_REV \
              --update-input charon/rust-overlay \
              --update-input hax \
              --update-input crane
